<?php
// $Id$

/**
 * @file
 * job scheduler module.
 */

define('JOB_SCHEDULER_REQUEST_TIME', time());

/**
 * Implementation of hook_cron().
 */
function job_scheduler_cron() {
  job_scheduler()->cron();
}

/**
 * Return a JobScheduler object.
 */
function job_scheduler() {
  static $included;
  if (!$included) {
    require './'. drupal_get_path('module', 'job_scheduler') ."/JobScheduler.inc";
    $included = TRUE;
  }
  return JobScheduler::instance();
}
